name: Java CI with Maven and SonarCloud

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn test -Dtest=ProgramaTesteUnitario

      - name: Download and unzip SonarScanner
        run: |
          curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip -q /tmp/sonar-scanner.zip -d ~/.sonar/

      - name: Configure SonarScanner path
        run: echo "export PATH=\"$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin:\$PATH\"" >> $GITHUB_ENV

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=AlissonRayanss_Gestao-e-Qualidade-de-Software-A3 \
            -Dsonar.organization=alissonrayanss \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.java.binaries=target/classes
