name: Java CI with Maven

on:
  push:
    branches:
      - main
      - developer
      - release
  pull_request:
    branches:
      - main
      - developer
      - release

jobs:
  Preflight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - run: |
          commit_message=$(git log -1 --pretty=format:"%s")
          echo "$commit_message" | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+$' || (echo "Commit message validation failed" && exit 1)

  Build:
    runs-on: ubuntu-latest
    needs: Preflight

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - run: mvn -B package --file pom.xml

  Test:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - run: mvn test -Dtest=ProgramaTesteUnitario

  SonarCloud:
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: |
          curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip /tmp/sonar-scanner.zip -d ~/.sonar/
          echo 'export PATH="$PATH:$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin"' >> $GITHUB_ENV

      - name: Run SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.sonar/sonar-scanner-4.6.2.2472-linux/bin"
          sonar-scanner \
            -Dsonar.projectKey=AlissonRayanss_Gestao-e-Qualidade-de-Software-A3 \
            -Dsonar.organization=alissonrayanss \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.java.binaries=target/classes
