name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Get last tag
      id: get_last_tag
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0)
        echo "::set-output name=last_tag::$LAST_TAG"
      
    - name: Get commit messages
      run: |
        git log $LAST_TAG..HEAD --no-decorate --pretty=format:"%s" > messages.txt
        cat messages.txt

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run unit tests
      run: mvn test 

    - name: Check commit messages
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          git log --format=%s ${{ github.event.before }}..${{ github.sha }} | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$"
        elif [ "${{ github.event_name }}" == "push" ]; then
          git log --format=%s $LAST_TAG..HEAD --no-decorate --pretty=format:"%s" | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$"
        else
          echo "Unsupported event: ${{ github.event_name }}"
        fi
