name: Java CI with Maven

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  Preflight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Get last tag
        id: get_last_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "::set-output name=last_tag::$LAST_TAG"
      
      - name: Fetch tags
        run: git fetch --tags
      
      - name: Get commit messages
        run: |
          git log ${{ steps.get_last_tag.outputs.last_tag }}..HEAD --no-decorate --pretty=format:"%s"    
          
      - name: Verificar mensagens de commit
        run: |
          INVALID_MESSAGES=()
          for COMMIT in $(git log v0.0.0..HEAD --format=%s); do
            echo "Verificando mensagem de commit: $COMMIT"
            if ! [[ "$COMMIT" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?: .*$ ]]; then
              echo "Mensagem de commit inválida: $COMMIT"
              INVALID_MESSAGES+=("$COMMIT")
            fi
          done
          if [ ${#INVALID_MESSAGES[@]} -gt 0 ]; then
            echo "Mensagens de commit inválidas encontradas:"
            for INVALID_MESSAGE in "${INVALID_MESSAGES[@]}"; do
              echo "- $INVALID_MESSAGE"
            done
            exit 1
          else
            echo "Todas as mensagens de commit são válidas."
          fi

  Build:
    runs-on: ubuntu-latest
    needs: Preflight

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  Teste:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run unit tests
        run: mvn test 
