name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check commit messages
        run: |
          LAST_COMMIT=$(git rev-parse ${{ github.event.before }})
          COMMIT_MSG=$(git log --format=%s $LAST_COMMIT..HEAD | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$")
          if [ -z "$COMMIT_MSG" ]; then
            echo "Commit message validation failed."
          fi

      - name: Run Tests
        run: mvn test 

      - name: Build with Maven
        run: mvn -B package --file pom.xml
