name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
     
    - name: Run unit tests
      run: mvn test 
      
    - name: Get last tag
      id: get_last_tag
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "::set-output name=last_tag::$LAST_TAG"
      
    - name: Get commit messages
      run: |
        git fetch --tags
        git log v1.0.0..HEAD --no-decorate --pretty=format:"%s" > messages.txt
        cat messages.txt

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check commit messages
      run: |
        git log v1.0.0..${{ github.sha }} --format=%s | grep -E "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .*$" 
