name: Testes de Integração

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run preflight checks
      run: mvn clean verify

  build:
    needs: preflight
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run tests
      run: mvn test -Dtest=ProgramaTesteUnitario

    - name: Run integration tests
      run: mvn verify

    - name: Generate JaCoCo Report
      run: mvn jacoco:report

    - name: Upload JaCoCo Report to FTP
      uses: sebastianpopp/ftp-action@v1.1.0
      with:
        host: joaobsjunior.com.br
        user: aluno-ftp
        password: a1b2c3d4@  
        localDir: target/site/jacoco
        remoteDir: Gestao-e-Qualidade-de-Software-A3
       
